version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: european_languages_mongodb
    environment:
      MONGO_INITDB_DATABASE: european_languages_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - european_languages_network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: european_languages_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - european_languages_network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: european_languages_backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb:27017/european_languages_db
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=your_super_secret_session_key_change_this_in_production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - european_languages_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: european_languages_frontend
    environment:
      - VITE_API_URL=http://backend:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - european_languages_network
    restart: unless-stopped

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: european_languages_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - european_languages_network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  european_languages_network:
    driver: bridge